global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-smartshopadvisor:8000']
 
# Cargar reglas de alerta
rule_files:
  - "/etc/prometheus/rules/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
